version: '3.8'

services:
  # Demo Data Generator
  generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-data-generator
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=medinovai_demo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./config:/app/config:ro
      - ./data:/app/data
    depends_on:
      - postgres
      - redis
    networks:
      - demo-net
    command: ["npm", "run", "dev"]

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: demo-data-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medinovai_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro
    networks:
      - demo-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: demo-data-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - demo-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer (Database UI)
  adminer:
    image: adminer:latest
    container_name: demo-data-adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres
    networks:
      - demo-net

  # Redis Commander (Redis UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: demo-data-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - demo-net

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  demo-net:
    driver: bridge 